version: "3.7"

services:
  php:
    container_name: educat-php
    restart: always
    image: laravel-php
    volumes:
      - source:/app
      - storage:/app/storage/logs
    environment:
       - APP_NAME="EDUCAT"
       - APP_REALM="EDUCAT"
       - APP_URL="https://educat.$DOMAINNAME"
       - APP_DEV_URL="https://dev-educat.$DOMAINNAME"
       - APP_DEBUG=false
       - DB_HOST=172.17.0.1
       - DB_PORT=3306
       - DB_DATABASE=$DB_EDUCAT_DATABASE
       - DB_USERNAME=$DB_EDUCAT_USERNAME
       - DB_PASSWORD=$DB_EDUCAT_PASSWORD
    networks:
       - backend

  nginx:
    container_name: educat-nginx
    restart: always
    image: laravel-nginx
    volumes:
      - source:/app
      - storage:/app/storage/logs
    depends_on:
      - php
    networks:
      - backend
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.http.routers.educat.entrypoints=websecure"
      - "traefik.http.routers.educat.rule=Host(`educat.${DOMAINNAME}`)"
      - "traefik.http.routers.educat.tls=true"
      - "traefik.http.routers.educat.service=educat"

      - "traefik.http.services.educat.loadbalancer.server.port=80"

  composer:
    container_name: educat-composer
    image: laravel-composer
    volumes:
      - source:/app
      - storage:/app/storage/logs
    working_dir: /app

  node:
    container_name: educat-node
    image: laravel-node
    volumes:
      - source:/app
      - storage:/app/storage/logs
    working_dir: /app

volumes:
  source:
    name: educat-source
  storage:
    name: educat-storage

networks:
  backend:
  web:
    external: true


